### PR TITLE
Corections to meta extension

### PR DESCRIPTION
**Pull request by arjanmels**
Correct oder to or and numerals in example to keys .

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by ghost — CHANGES_REQUESTED** [review]
You are right, there should be no numbers.
But in your correction, you assigned the topic id "alexa" to the "HomeKit" key. While this is technically allowed according to the extension specification, I actually intended to assign the "Alexa" key value to the "alexa" topic, and the "HomeKit" key value to the "homekit" topic.

Edit: So what i mean is: you changed the numeral "0" to "alexa", while it would me more appropriate to change "0" to "homekit" and "1" to "alexa".

**Comment by arjanmels** [comment]
Sory, my mistake

**Comment by EP-u-NW** [comment]
Can you make an other commit to fix this :) ?

**Comment by arjanmels** [comment]
Corrected.

**Review by ghost — APPROVED** [review]

**Review by davidgraeff — APPROVED** [review]

**Pull request merged**
