### PR TITLE
Fix extension suffix typo

### PR DESCRIPTION
**Pull request by ThomDietrich**
Do not merge jet. What's the message here? Are we disallowing the project name: https://the-most-amazing-homie-extension.com?

### CODE REVIEW

**Comment by davidgraeff** [comment]
"example.org.homie" is disallowed (suffix may not be "homie" on its own)
"homie.org.my-extension" is disallowed (domain may not me homie)

**Comment by davidgraeff** [comment]
Any progress on this front? :)

**Comment by ThomDietrich** [comment]
I am unsure if we should and can forbid "homie" in the domain name...

**Comment by davidgraeff** [comment]
At some point a homie domain might be registered for this convention. I just want to avoid the situation that someone has extensions with ids like "org.homie.extname" or whatever the official domain would be.

**Comment by ThomDietrich** [comment]
Good idea I guess. Okay let's have it in the convention.

**Pull request merged**
