### PR TITLE
single description topic

### PR DESCRIPTION
**Pull request by Tieske**

### CODE REVIEW

**Comment by Tieske** [comment]
I created a bridge that converts Homie v4 devices to Homie v5, based on the proposal in this PR. 

It will collect the config (from topic `homie/#`) and post it on as a v5 device on `homie5/#`.

Repo is here: https://github.com/Tieske/homie45. It has a docker script that shows how to quickly test it.

**Comment by ThomDietrich** [comment]
Hey, thanks for your efforts!
Why is this in a separate file? Makes it hard to track differences and changes.

**Review by schaze — APPROVED** [review]

**Comment by Tieske** [comment]
@ThomDietrich because there are also PR's for the v4 version. This seemed best. Open to alternatives though...
(also mentioned here: https://gitter.im/homie-iot/convention?at=6383cd26426f9311ffc47d1c )

I guess if we quit making changes/clarifications to v4 then we could use the same file.

**Review by schaze — APPROVED** [review]

**Comment by Tieske** [comment]
closing this in favor of #237 .

**Pull request closed without merging**
