### PR TITLE
More realistic array example

### PR DESCRIPTION
**Pull request by davidgraeff**
More realistic array example. You are using arrays if you have tons of subjects, not just two

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Is that all? The `lights` example is used more than once and you'd need to adapt them all.
I like your intention but an ledstrip doesn't match @marvinroger 's example of an RC car.

Maybe easier: You could leave the original text and add the led strip example below.

**Comment by timpur** [comment]
If your going to make the effort to make a change, may as well enhance the examples with it ect... ?
Sorry David.

**Comment by davidgraeff** [comment]
The RC car should have a ledstrip then :)

You can name the elements of the given array ("backlight", "frontlight"), it feels more like an anti-example of an array.

**Comment by ThomDietrich** [comment]
How about

grafik

**Comment by davidgraeff** [comment]
The Array spec gets an overhaul soon anyway, I guess. Closing this PR

**Pull request closed without merging**
